
project: main.o FormulaOneTeam.o InputStorage.o Time.o Location.o Date.o Logistics.o EuropeanTransport.o NonEuropeanTransportEquipment.o NonEuropeanTransportCar.o Aerodynamics.o CarBuild.o CarBuilder.o Chassis.o CockpitErgonomics.o Component.o ComponentTraverser.o ConcreteCarBuilder.o Electronics.o Engine.o EngineeringTeam.o Suspension.o Traverser.o WarningSystem.o HighTyreDegredationStrategy.o OriginalStrategy.o RepairsNeededStrategy.o Strategy.o VeryWetStrategy.o WetStrategy.o Car.o CheckeredFlag.o FlagObserver.o Practice.o Qualifying.o Race.o RedFlag.o YellowFlag.o Results.o ResultConstructor.o ResultDriver.o ElectronicsTesting.o EngineTesting.o InteriorTesting.o SuspensionTesting.o Testing.o WindTunnelTesting.o
	g++ main.o FormulaOneTeam.o InputStorage.o Time.o Location.o Date.o Logistics.o EuropeanTransport.o NonEuropeanTransportEquipment.o NonEuropeanTransportCar.o Aerodynamics.o CarBuild.o CarBuilder.o Chassis.o CockpitErgonomics.o Component.o ComponentTraverser.o ConcreteCarBuilder.o Electronics.o Engine.o EngineeringTeam.o Suspension.o Traverser.o WarningSystem.o HighTyreDegredationStrategy.o OriginalStrategy.o RepairsNeededStrategy.o Strategy.o VeryWetStrategy.o WetStrategy.o Car.o CheckeredFlag.o FlagObserver.o Practice.o Qualifying.o Race.o RedFlag.o YellowFlag.o Results.o ResultConstructor.o ResultDriver.o ElectronicsTesting.o EngineTesting.o InteriorTesting.o SuspensionTesting.o Testing.o WindTunnelTesting.o -o project

main.o: main.cpp
	g++ -c main.cpp

FormulaOneTeam.o: FormulaOneTeam.cpp
	g++ -c FormulaOneTeam.cpp

InputStorage.o: InputStorage.cpp
	g++ -c InputStorage.cpp

Time.o: Time.cpp
	g++ -c Time.cpp

Location.o: Location.cpp
	g++ -c Location.cpp

Date.o: Date.cpp
	g++ -c Date.cpp

Logistics.o: Logistics.cpp
	g++ -c Logistics.cpp



EuropeanTransport.o: EuropeanTransport.cpp
	g++ -c EuropeanTransport.cpp

NonEuropeanTransportEqipment.o: NonEuropeanTransportEquipment.cpp
	g++ -c NonEuropeanTransportEquipment.cpp

NonEuropeanTransportCar.o: NonEuropeanTransportCar.cpp
	g++ -c NonEuropeanTransportCar.cpp

Aerodynamics.o: Aerodynamics.cpp
	g++ -c Aerodynamics.cpp

CarBuild.o: CarBuild.cpp
	g++ -c CarBuild.cpp

CarBuilder.o: CarBuilder.cpp
	g++ -c CarBuilder.cpp

Chassis.o: Chassis.cpp
	g++ -c Chassis.cpp

CockpitErgonomics.o: CockpitErgonomics.cpp
	g++ -c CockpitErgonomics.cpp

Component.o: Component.cpp
	g++ -c Component.cpp

ComponentTraverser.o: ComponentTraverser.cpp
	g++ -c ComponentTraverser.cpp

ConcreteCarBuilder.o: ConcreteCarBuilder.cpp
	g++ -c ConcreteCarBuilder.cpp

Electronics.o: Electronics.cpp
	g++ -c Electronics.cpp

Engine.o: Engine.cpp
	g++ -c Engine.cpp

EngineeringTeam.o: EngineeringTeam.cpp
	g++ -c EngineeringTeam.cpp

Suspension.o: Suspension.cpp
	g++ -c Suspension.cpp

Traverser.o: Traverser.cpp
	g++ -c Traverser.cpp

WarningSystem.o: WarningSystem.cpp
	g++ -c WarningSystem.cpp

HighTyreDegredationStrategy.o: HighTyreDegredationStrategy.cpp
	g++ -c HighTyreDegredationStrategy.cpp

OriginalStrategy.o: OriginalStrategy.cpp
	g++ -c OriginalStrategy.cpp

RepairsNeededStrategy.o: RepairsNeededStrategy.cpp
	g++ -c RepairsNeededStrategy.cpp

Strategy.o: Strategy.cpp
	g++ -c Strategy.cpp

VeryWetStrategy.o: VeryWetStrategy.cpp
	g++ -c VeryWetStrategy.cpp

WetStrategy.o: WetStrategy.cpp
	g++ -c WetStrategy.cpp

Car.o: Car.cpp
	g++ -c Car.cpp

CheckeredFlag.o: CheckeredFlag.cpp
	g++ -c CheckeredFlag.cpp

FlagObserver.o: FlagObserver.cpp
	g++ -c FlagObserver.cpp

Practice.o: Practice.cpp Track.h
	g++ -c Practice.cpp

Qualifying.o: Qualifying.cpp Track.h
	g++ -c Qualifying.cpp

Race.o: Race.cpp Track.h
	g++ -c Race.cpp

RedFlag.o: RedFlag.cpp
	g++ -c RedFlag.cpp


YellowFlag.o: YellowFlag.cpp
	g++ -c YellowFlag.cpp

Results.o: Results.cpp
	g++ -c Results.cpp

ResultConstructor.o: ResultConstructor.cpp
	g++ -c ResultConstructor.cpp

ResultDriver.o: ResultDriver.cpp
	g++ -c ResultDriver.cpp

ElectronicsTesting.o: ElectronicsTesting.cpp
	g++ -c ElectronicsTesting.cpp

EngineTesting.o: EngineTesting.cpp
	g++ -c EngineTesting.cpp

InteriorTesting.o: InteriorTesting.cpp
	g++ -c InteriorTesting.cpp

SuspensionTesting.o: SuspensionTesting.cpp
	g++ -c SuspensionTesting.cpp

Testing.o: Testing.cpp
	g++ -c Testing.cpp

WindTunnelTesting.o: WindTunnelTesting.cpp
	g++ -c WindTunnelTesting.cpp

clean:
	rm *.o project

run:
	./project
